// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileStats_WebAPIs.DBContext;

#nullable disable

namespace MobileStats_WebAPIs.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220907164431_AddedDBAndTablesWithRecords")]
    partial class AddedDBAndTablesWithRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobileStats_WebAPIs.Models.MobileBrands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Added_dt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Brand_id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remove_dt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_dt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MobileBrands");
                });

            modelBuilder.Entity("MobileStats_WebAPIs.Models.MobileDevices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Battery_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Battery_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camera_pixels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deleted_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Device_id")
                        .HasColumnType("int");

                    b.Property<int?>("Dis_Price")
                        .HasColumnType("int");

                    b.Property<string>("Display_resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Display_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max_discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Os")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Released_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video_pixels")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MobileDevices");
                });

            modelBuilder.Entity("MobileStats_WebAPIs.Models.MobileSellingRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Device_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Given_discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMEI_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDiscountApplied")
                        .HasColumnType("bit");

                    b.Property<string>("MaxDiscount_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Max_discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Original_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Selling_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Selling_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionUpdated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transaction_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MobileSellingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
